// ─── XKDG Bazi Calculator — Cities reference data (EXHAUSTIVE) ─────────────
// ~500 cities covering: all world capitals, major metros >1M population,
// complete Italian regional coverage, Chinese provinces, Japanese prefectures,
// US state capitals + major cities, comprehensive global coverage.
//
// Format: { name, lng, utc }
//   name : "City, Country/Region"
//   lng  : decimal longitude (°E positive, °W negative, 2 decimals)
//   utc  : UTC offset in hours, WINTER standard time (DST handled separately)
//
// Sources: Wikipedia coordinates + IANA tz database standard offset.
// Last updated: 2026-05-15

window.CITY_LIST = [
  { region: 'Europe — Italy', cities: [
    { name: 'Rome, Italy',            lng:  12.49, utc:  1 },
    { name: 'Milan, Italy',           lng:   9.19, utc:  1 },
    { name: 'Naples, Italy',          lng:  14.25, utc:  1 },
    { name: 'Turin, Italy',           lng:   7.69, utc:  1 },
    { name: 'Palermo, Italy',         lng:  13.36, utc:  1 },
    { name: 'Genoa, Italy',           lng:   8.93, utc:  1 },
    { name: 'Bologna, Italy',         lng:  11.34, utc:  1 },
    { name: 'Florence, Italy',        lng:  11.25, utc:  1 },
    { name: 'Bari, Italy',            lng:  16.87, utc:  1 },
    { name: 'Catania, Italy',         lng:  15.09, utc:  1 },
    { name: 'Venice, Italy',          lng:  12.33, utc:  1 },
    { name: 'Verona, Italy',          lng:  10.99, utc:  1 },
    { name: 'Messina, Italy',         lng:  15.55, utc:  1 },
    { name: 'Padua, Italy',           lng:  11.88, utc:  1 },
    { name: 'Trieste, Italy',         lng:  13.77, utc:  1 },
    { name: 'Brescia, Italy',         lng:  10.22, utc:  1 },
    { name: 'Parma, Italy',           lng:  10.33, utc:  1 },
    { name: 'Modena, Italy',          lng:  10.93, utc:  1 },
    { name: 'Reggio Calabria, Italy', lng:  15.65, utc:  1 },
    { name: 'Perugia, Italy',         lng:  12.39, utc:  1 },
    { name: 'Livorno, Italy',         lng:  10.31, utc:  1 },
    { name: 'Cagliari, Italy',        lng:   9.12, utc:  1 },
    { name: 'Foggia, Italy',          lng:  15.55, utc:  1 },
    { name: 'Salerno, Italy',         lng:  14.77, utc:  1 },
    { name: 'Ravenna, Italy',         lng:  12.20, utc:  1 },
    { name: 'Ferrara, Italy',         lng:  11.62, utc:  1 },
    { name: 'Sassari, Italy',         lng:   8.56, utc:  1 },
    { name: 'Monza, Italy',           lng:   9.27, utc:  1 },
    { name: 'Bergamo, Italy',         lng:   9.67, utc:  1 },
    { name: 'Trento, Italy',          lng:  11.12, utc:  1 },
    { name: 'Vicenza, Italy',         lng:  11.55, utc:  1 },
    { name: 'Bolzano, Italy',         lng:  11.35, utc:  1 },
    { name: 'Ancona, Italy',          lng:  13.51, utc:  1 },
    { name: 'Udine, Italy',           lng:  13.24, utc:  1 },
    { name: 'Arezzo, Italy',          lng:  11.88, utc:  1 },
    { name: 'Pisa, Italy',            lng:  10.40, utc:  1 },
    { name: 'Lecce, Italy',           lng:  18.17, utc:  1 },
    { name: 'Pescara, Italy',         lng:  14.21, utc:  1 },
    { name: 'Catanzaro, Italy',       lng:  16.59, utc:  1 },
    { name: 'L\'Aquila, Italy',       lng:  13.40, utc:  1 },
    { name: 'Campobasso, Italy',      lng:  14.66, utc:  1 },
    { name: 'Potenza, Italy',         lng:  15.80, utc:  1 },
    { name: 'Aosta, Italy',           lng:   7.32, utc:  1 },
  ]},
  { region: 'Europe — Western', cities: [
    { name: 'London, UK',             lng:  -0.13, utc:  0 },
    { name: 'Birmingham, UK',         lng:  -1.90, utc:  0 },
    { name: 'Manchester, UK',         lng:  -2.24, utc:  0 },
    { name: 'Leeds, UK',              lng:  -1.55, utc:  0 },
    { name: 'Glasgow, UK',            lng:  -4.25, utc:  0 },
    { name: 'Edinburgh, UK',          lng:  -3.19, utc:  0 },
    { name: 'Liverpool, UK',          lng:  -2.98, utc:  0 },
    { name: 'Bristol, UK',            lng:  -2.59, utc:  0 },
    { name: 'Sheffield, UK',          lng:  -1.47, utc:  0 },
    { name: 'Newcastle, UK',          lng:  -1.61, utc:  0 },
    { name: 'Belfast, UK',            lng:  -5.93, utc:  0 },
    { name: 'Cardiff, UK',            lng:  -3.18, utc:  0 },
    { name: 'Paris, France',          lng:   2.35, utc:  1 },
    { name: 'Marseille, France',      lng:   5.37, utc:  1 },
    { name: 'Lyon, France',           lng:   4.84, utc:  1 },
    { name: 'Toulouse, France',       lng:   1.44, utc:  1 },
    { name: 'Nice, France',           lng:   7.27, utc:  1 },
    { name: 'Nantes, France',         lng:  -1.55, utc:  1 },
    { name: 'Strasbourg, France',     lng:   7.75, utc:  1 },
    { name: 'Montpellier, France',    lng:   3.88, utc:  1 },
    { name: 'Bordeaux, France',       lng:  -0.58, utc:  1 },
    { name: 'Lille, France',          lng:   3.06, utc:  1 },
    { name: 'Rennes, France',         lng:  -1.68, utc:  1 },
    { name: 'Berlin, Germany',        lng:  13.41, utc:  1 },
    { name: 'Hamburg, Germany',       lng:   9.99, utc:  1 },
    { name: 'Munich, Germany',        lng:  11.58, utc:  1 },
    { name: 'Cologne, Germany',       lng:   6.96, utc:  1 },
    { name: 'Frankfurt, Germany',     lng:   8.68, utc:  1 },
    { name: 'Stuttgart, Germany',     lng:   9.18, utc:  1 },
    { name: 'Düsseldorf, Germany',    lng:   6.78, utc:  1 },
    { name: 'Dortmund, Germany',      lng:   7.47, utc:  1 },
    { name: 'Essen, Germany',         lng:   7.01, utc:  1 },
    { name: 'Leipzig, Germany',       lng:  12.37, utc:  1 },
    { name: 'Bremen, Germany',        lng:   8.80, utc:  1 },
    { name: 'Dresden, Germany',       lng:  13.74, utc:  1 },
    { name: 'Hanover, Germany',       lng:   9.74, utc:  1 },
    { name: 'Nuremberg, Germany',     lng:  11.08, utc:  1 },
    { name: 'Amsterdam, Netherlands', lng:   4.90, utc:  1 },
    { name: 'Rotterdam, Netherlands', lng:   4.48, utc:  1 },
    { name: 'The Hague, Netherlands', lng:   4.30, utc:  1 },
    { name: 'Utrecht, Netherlands',   lng:   5.12, utc:  1 },
    { name: 'Brussels, Belgium',      lng:   4.35, utc:  1 },
    { name: 'Antwerp, Belgium',       lng:   4.40, utc:  1 },
    { name: 'Ghent, Belgium',         lng:   3.72, utc:  1 },
    { name: 'Madrid, Spain',          lng:  -3.70, utc:  1 },
    { name: 'Barcelona, Spain',       lng:   2.17, utc:  1 },
    { name: 'Valencia, Spain',        lng:  -0.38, utc:  1 },
    { name: 'Seville, Spain',         lng:  -5.98, utc:  1 },
    { name: 'Zaragoza, Spain',        lng:  -0.88, utc:  1 },
    { name: 'Málaga, Spain',          lng:  -4.42, utc:  1 },
    { name: 'Bilbao, Spain',          lng:  -2.93, utc:  1 },
    { name: 'Lisbon, Portugal',       lng:  -9.14, utc:  0 },
    { name: 'Porto, Portugal',        lng:  -8.61, utc:  0 },
    { name: 'Dublin, Ireland',        lng:  -6.27, utc:  0 },
    { name: 'Cork, Ireland',          lng:  -8.47, utc:  0 },
    { name: 'Zurich, Switzerland',    lng:   8.55, utc:  1 },
    { name: 'Geneva, Switzerland',    lng:   6.14, utc:  1 },
    { name: 'Basel, Switzerland',     lng:   7.59, utc:  1 },
    { name: 'Bern, Switzerland',      lng:   7.45, utc:  1 },
    { name: 'Vienna, Austria',        lng:  16.37, utc:  1 },
    { name: 'Graz, Austria',          lng:  15.44, utc:  1 },
    { name: 'Linz, Austria',          lng:  14.29, utc:  1 },
    { name: 'Salzburg, Austria',      lng:  13.04, utc:  1 },
    { name: 'Innsbruck, Austria',     lng:  11.39, utc:  1 },
    { name: 'Luxembourg City',        lng:   6.13, utc:  1 },
    { name: 'Monaco',                 lng:   7.42, utc:  1 },
  ]},
  { region: 'Europe — Northern', cities: [
    { name: 'Stockholm, Sweden',      lng:  18.07, utc:  1 },
    { name: 'Gothenburg, Sweden',     lng:  11.97, utc:  1 },
    { name: 'Malmö, Sweden',          lng:  13.00, utc:  1 },
    { name: 'Oslo, Norway',           lng:  10.75, utc:  1 },
    { name: 'Bergen, Norway',         lng:   5.32, utc:  1 },
    { name: 'Trondheim, Norway',      lng:  10.40, utc:  1 },
    { name: 'Copenhagen, Denmark',    lng:  12.57, utc:  1 },
    { name: 'Aarhus, Denmark',        lng:  10.20, utc:  1 },
    { name: 'Helsinki, Finland',      lng:  24.94, utc:  2 },
    { name: 'Espoo, Finland',         lng:  24.65, utc:  2 },
    { name: 'Tampere, Finland',       lng:  23.76, utc:  2 },
    { name: 'Reykjavik, Iceland',     lng: -21.90, utc:  0 },
    { name: 'Tallinn, Estonia',       lng:  24.75, utc:  2 },
    { name: 'Riga, Latvia',           lng:  24.11, utc:  2 },
    { name: 'Vilnius, Lithuania',     lng:  25.28, utc:  2 },
  ]},
  { region: 'Europe — Central & Eastern', cities: [
    { name: 'Warsaw, Poland',         lng:  21.02, utc:  1 },
    { name: 'Kraków, Poland',         lng:  19.94, utc:  1 },
    { name: 'Łódź, Poland',           lng:  19.46, utc:  1 },
    { name: 'Wrocław, Poland',        lng:  17.04, utc:  1 },
    { name: 'Poznań, Poland',         lng:  16.93, utc:  1 },
    { name: 'Gdańsk, Poland',         lng:  18.65, utc:  1 },
    { name: 'Prague, Czechia',        lng:  14.42, utc:  1 },
    { name: 'Brno, Czechia',          lng:  16.61, utc:  1 },
    { name: 'Bratislava, Slovakia',   lng:  17.11, utc:  1 },
    { name: 'Budapest, Hungary',      lng:  19.04, utc:  1 },
    { name: 'Debrecen, Hungary',      lng:  21.63, utc:  1 },
    { name: 'Bucharest, Romania',     lng:  26.10, utc:  2 },
    { name: 'Cluj-Napoca, Romania',   lng:  23.60, utc:  2 },
    { name: 'Timișoara, Romania',     lng:  21.23, utc:  2 },
    { name: 'Sofia, Bulgaria',        lng:  23.32, utc:  2 },
    { name: 'Athens, Greece',         lng:  23.73, utc:  2 },
    { name: 'Thessaloniki, Greece',   lng:  22.94, utc:  2 },
    { name: 'Belgrade, Serbia',       lng:  20.45, utc:  1 },
    { name: 'Zagreb, Croatia',        lng:  15.98, utc:  1 },
    { name: 'Ljubljana, Slovenia',    lng:  14.51, utc:  1 },
    { name: 'Sarajevo, Bosnia',       lng:  18.41, utc:  1 },
    { name: 'Skopje, N. Macedonia',   lng:  21.43, utc:  1 },
    { name: 'Tirana, Albania',        lng:  19.82, utc:  1 },
    { name: 'Kyiv, Ukraine',          lng:  30.52, utc:  2 },
    { name: 'Kharkiv, Ukraine',       lng:  36.23, utc:  2 },
    { name: 'Odesa, Ukraine',         lng:  30.73, utc:  2 },
    { name: 'Minsk, Belarus',         lng:  27.57, utc:  3 },
    { name: 'Chișinău, Moldova',      lng:  28.86, utc:  2 },
    { name: 'Moscow, Russia',         lng:  37.62, utc:  3 },
    { name: 'St. Petersburg, Russia', lng:  30.34, utc:  3 },
    { name: 'Novosibirsk, Russia',    lng:  82.93, utc:  7 },
    { name: 'Yekaterinburg, Russia',  lng:  60.61, utc:  5 },
    { name: 'Kazan, Russia',          lng:  49.12, utc:  3 },
    { name: 'Vladivostok, Russia',    lng: 131.87, utc: 10 },
    { name: 'Istanbul, Turkey',       lng:  28.98, utc:  3 },
    { name: 'Ankara, Turkey',         lng:  32.86, utc:  3 },
    { name: 'Izmir, Turkey',          lng:  27.14, utc:  3 },
    { name: 'Nicosia, Cyprus',        lng:  33.36, utc:  2 },
    { name: 'Valletta, Malta',        lng:  14.51, utc:  1 },
  ]},
  { region: 'Asia — East Asia', cities: [
    { name: 'Tokyo, Japan',           lng: 139.65, utc:  9 },
    { name: 'Yokohama, Japan',        lng: 139.64, utc:  9 },
    { name: 'Osaka, Japan',           lng: 135.50, utc:  9 },
    { name: 'Nagoya, Japan',          lng: 136.91, utc:  9 },
    { name: 'Sapporo, Japan',         lng: 141.35, utc:  9 },
    { name: 'Fukuoka, Japan',         lng: 130.42, utc:  9 },
    { name: 'Kobe, Japan',            lng: 135.18, utc:  9 },
    { name: 'Kyoto, Japan',           lng: 135.77, utc:  9 },
    { name: 'Kawasaki, Japan',        lng: 139.72, utc:  9 },
    { name: 'Hiroshima, Japan',       lng: 132.46, utc:  9 },
    { name: 'Sendai, Japan',          lng: 140.87, utc:  9 },
    { name: 'Beijing, China',         lng: 116.41, utc:  8 },
    { name: 'Shanghai, China',        lng: 121.47, utc:  8 },
    { name: 'Guangzhou, China',       lng: 113.26, utc:  8 },
    { name: 'Shenzhen, China',        lng: 114.06, utc:  8 },
    { name: 'Chengdu, China',         lng: 104.07, utc:  8 },
    { name: 'Chongqing, China',       lng: 106.55, utc:  8 },
    { name: 'Tianjin, China',         lng: 117.20, utc:  8 },
    { name: 'Wuhan, China',           lng: 114.30, utc:  8 },
    { name: 'Nanjing, China',         lng: 118.78, utc:  8 },
    { name: 'Xi\'an, China',          lng: 108.93, utc:  8 },
    { name: 'Hangzhou, China',        lng: 120.16, utc:  8 },
    { name: 'Shenyang, China',        lng: 123.43, utc:  8 },
    { name: 'Harbin, China',          lng: 126.53, utc:  8 },
    { name: 'Dalian, China',          lng: 121.61, utc:  8 },
    { name: 'Qingdao, China',         lng: 120.38, utc:  8 },
    { name: 'Zhengzhou, China',       lng: 113.63, utc:  8 },
    { name: 'Jinan, China',           lng: 117.00, utc:  8 },
    { name: 'Changsha, China',        lng: 112.94, utc:  8 },
    { name: 'Kunming, China',         lng: 102.71, utc:  8 },
    { name: 'Ürümqi, China',          lng:  87.58, utc:  6 },
    { name: 'Lhasa, China',           lng:  91.13, utc:  8 },
    { name: 'Hong Kong',              lng: 114.18, utc:  8 },
    { name: 'Macau',                  lng: 113.54, utc:  8 },
    { name: 'Taipei, Taiwan',         lng: 121.57, utc:  8 },
    { name: 'Kaohsiung, Taiwan',      lng: 120.31, utc:  8 },
    { name: 'Seoul, S. Korea',        lng: 126.98, utc:  9 },
    { name: 'Busan, S. Korea',        lng: 129.08, utc:  9 },
    { name: 'Incheon, S. Korea',      lng: 126.71, utc:  9 },
    { name: 'Daegu, S. Korea',        lng: 128.60, utc:  9 },
    { name: 'Pyongyang, N. Korea',    lng: 125.75, utc:  9 },
    { name: 'Ulaanbaatar, Mongolia',  lng: 106.92, utc:  8 },
  ]},
  { region: 'Asia — Southeast Asia', cities: [
    { name: 'Bangkok, Thailand',      lng: 100.50, utc:  7 },
    { name: 'Chiang Mai, Thailand',   lng:  98.98, utc:  7 },
    { name: 'Singapore',              lng: 103.82, utc:  8 },
    { name: 'Jakarta, Indonesia',     lng: 106.85, utc:  7 },
    { name: 'Surabaya, Indonesia',    lng: 112.75, utc:  7 },
    { name: 'Bandung, Indonesia',     lng: 107.62, utc:  7 },
    { name: 'Medan, Indonesia',       lng:  98.67, utc:  7 },
    { name: 'Semarang, Indonesia',    lng: 110.42, utc:  7 },
    { name: 'Kuala Lumpur, Malaysia', lng: 101.69, utc:  8 },
    { name: 'George Town, Malaysia',  lng: 100.34, utc:  8 },
    { name: 'Manila, Philippines',    lng: 120.98, utc:  8 },
    { name: 'Quezon City, Philippines',lng:121.04, utc:  8 },
    { name: 'Davao, Philippines',     lng: 125.61, utc:  8 },
    { name: 'Cebu City, Philippines', lng: 123.89, utc:  8 },
    { name: 'Hanoi, Vietnam',         lng: 105.85, utc:  7 },
    { name: 'Ho Chi Minh City, Vietnam',lng:106.66,utc:  7 },
    { name: 'Da Nang, Vietnam',       lng: 108.22, utc:  7 },
    { name: 'Yangon, Myanmar',        lng:  96.16, utc:  6.5},
    { name: 'Mandalay, Myanmar',      lng:  96.08, utc:  6.5},
    { name: 'Naypyidaw, Myanmar',     lng:  96.13, utc:  6.5},
    { name: 'Phnom Penh, Cambodia',   lng: 104.92, utc:  7 },
    { name: 'Vientiane, Laos',        lng: 102.61, utc:  7 },
    { name: 'Bandar Seri Begawan, Brunei',lng:114.94,utc:8 },
    { name: 'Dili, Timor-Leste',      lng: 125.57, utc:  9 },
  ]},
  { region: 'Asia — South Asia', cities: [
    { name: 'Mumbai, India',          lng:  72.88, utc:  5.5},
    { name: 'Delhi, India',           lng:  77.21, utc:  5.5},
    { name: 'Bangalore, India',       lng:  77.59, utc:  5.5},
    { name: 'Kolkata, India',         lng:  88.36, utc:  5.5},
    { name: 'Chennai, India',         lng:  80.27, utc:  5.5},
    { name: 'Hyderabad, India',       lng:  78.49, utc:  5.5},
    { name: 'Ahmedabad, India',       lng:  72.58, utc:  5.5},
    { name: 'Pune, India',            lng:  73.86, utc:  5.5},
    { name: 'Jaipur, India',          lng:  75.79, utc:  5.5},
    { name: 'Surat, India',           lng:  72.83, utc:  5.5},
    { name: 'Lucknow, India',         lng:  80.95, utc:  5.5},
    { name: 'Kanpur, India',          lng:  80.35, utc:  5.5},
    { name: 'Nagpur, India',          lng:  79.09, utc:  5.5},
    { name: 'Visakhapatnam, India',   lng:  83.30, utc:  5.5},
    { name: 'Indore, India',          lng:  75.86, utc:  5.5},
    { name: 'Thane, India',           lng:  72.97, utc:  5.5},
    { name: 'Bhopal, India',          lng:  77.41, utc:  5.5},
    { name: 'Patna, India',           lng:  85.14, utc:  5.5},
    { name: 'Vadodara, India',        lng:  73.21, utc:  5.5},
    { name: 'Karachi, Pakistan',      lng:  67.01, utc:  5 },
    { name: 'Lahore, Pakistan',       lng:  74.36, utc:  5 },
    { name: 'Faisalabad, Pakistan',   lng:  73.08, utc:  5 },
    { name: 'Rawalpindi, Pakistan',   lng:  73.06, utc:  5 },
    { name: 'Islamabad, Pakistan',    lng:  73.05, utc:  5 },
    { name: 'Peshawar, Pakistan',     lng:  71.58, utc:  5 },
    { name: 'Dhaka, Bangladesh',      lng:  90.41, utc:  6 },
    { name: 'Chittagong, Bangladesh', lng:  91.83, utc:  6 },
    { name: 'Kathmandu, Nepal',       lng:  85.32, utc:  5.75},
    { name: 'Colombo, Sri Lanka',     lng:  79.86, utc:  5.5},
    { name: 'Thimphu, Bhutan',        lng:  89.64, utc:  6 },
    { name: 'Malé, Maldives',         lng:  73.51, utc:  5 },
    { name: 'Kabul, Afghanistan',     lng:  69.17, utc:  4.5},
  ]},
  { region: 'Asia — Central & West Asia', cities: [
    { name: 'Tashkent, Uzbekistan',   lng:  69.30, utc:  5 },
    { name: 'Almaty, Kazakhstan',     lng:  76.95, utc:  6 },
    { name: 'Astana, Kazakhstan',     lng:  71.47, utc:  6 },
    { name: 'Ashgabat, Turkmenistan', lng:  58.38, utc:  5 },
    { name: 'Bishkek, Kyrgyzstan',    lng:  74.59, utc:  6 },
    { name: 'Dushanbe, Tajikistan',   lng:  68.78, utc:  5 },
    { name: 'Tehran, Iran',           lng:  51.39, utc:  3.5},
    { name: 'Mashhad, Iran',          lng:  59.57, utc:  3.5},
    { name: 'Isfahan, Iran',          lng:  51.68, utc:  3.5},
    { name: 'Tabriz, Iran',           lng:  46.29, utc:  3.5},
    { name: 'Baghdad, Iraq',          lng:  44.36, utc:  3 },
    { name: 'Basra, Iraq',            lng:  47.78, utc:  3 },
    { name: 'Damascus, Syria',        lng:  36.29, utc:  2 },
    { name: 'Aleppo, Syria',          lng:  37.16, utc:  2 },
    { name: 'Beirut, Lebanon',        lng:  35.49, utc:  2 },
    { name: 'Amman, Jordan',          lng:  35.95, utc:  2 },
    { name: 'Jerusalem, Israel',      lng:  35.22, utc:  2 },
    { name: 'Tel Aviv, Israel',       lng:  34.78, utc:  2 },
    { name: 'Riyadh, Saudi Arabia',   lng:  46.68, utc:  3 },
    { name: 'Jeddah, Saudi Arabia',   lng:  39.19, utc:  3 },
    { name: 'Mecca, Saudi Arabia',    lng:  39.83, utc:  3 },
    { name: 'Medina, Saudi Arabia',   lng:  39.61, utc:  3 },
    { name: 'Dubai, UAE',             lng:  55.27, utc:  4 },
    { name: 'Abu Dhabi, UAE',         lng:  54.37, utc:  4 },
    { name: 'Doha, Qatar',            lng:  51.53, utc:  3 },
    { name: 'Kuwait City, Kuwait',    lng:  47.98, utc:  3 },
    { name: 'Manama, Bahrain',        lng:  50.59, utc:  3 },
    { name: 'Muscat, Oman',           lng:  58.41, utc:  4 },
    { name: 'Sana\'a, Yemen',         lng:  44.21, utc:  3 },
    { name: 'Aden, Yemen',            lng:  45.04, utc:  3 },
  ]},
  { region: 'North America — USA', cities: [
    { name: 'New York, USA',          lng: -74.01, utc: -5 },
    { name: 'Los Angeles, USA',       lng:-118.24, utc: -8 },
    { name: 'Chicago, USA',           lng: -87.65, utc: -6 },
    { name: 'Houston, USA',           lng: -95.37, utc: -6 },
    { name: 'Phoenix, USA',           lng:-112.07, utc: -7 },
    { name: 'Philadelphia, USA',      lng: -75.17, utc: -5 },
    { name: 'San Antonio, USA',       lng: -98.49, utc: -6 },
    { name: 'San Diego, USA',         lng:-117.16, utc: -8 },
    { name: 'Dallas, USA',            lng: -96.80, utc: -6 },
    { name: 'San Jose, USA',          lng:-121.89, utc: -8 },
    { name: 'Austin, USA',            lng: -97.74, utc: -6 },
    { name: 'Jacksonville, USA',      lng: -81.66, utc: -5 },
    { name: 'Fort Worth, USA',        lng: -97.33, utc: -6 },
    { name: 'Columbus, USA',          lng: -83.00, utc: -5 },
    { name: 'Charlotte, USA',         lng: -80.84, utc: -5 },
    { name: 'San Francisco, USA',     lng:-122.42, utc: -8 },
    { name: 'Indianapolis, USA',      lng: -86.16, utc: -5 },
    { name: 'Seattle, USA',           lng:-122.33, utc: -8 },
    { name: 'Denver, USA',            lng:-104.99, utc: -7 },
    { name: 'Washington DC, USA',     lng: -77.04, utc: -5 },
    { name: 'Boston, USA',            lng: -71.06, utc: -5 },
    { name: 'Nashville, USA',         lng: -86.78, utc: -6 },
    { name: 'Detroit, USA',           lng: -83.05, utc: -5 },
    { name: 'Portland, USA',          lng:-122.68, utc: -8 },
    { name: 'Las Vegas, USA',         lng:-115.14, utc: -8 },
    { name: 'Memphis, USA',           lng: -90.05, utc: -6 },
    { name: 'Baltimore, USA',         lng: -76.61, utc: -5 },
    { name: 'Milwaukee, USA',         lng: -87.91, utc: -6 },
    { name: 'Atlanta, USA',           lng: -84.39, utc: -5 },
    { name: 'Miami, USA',             lng: -80.19, utc: -5 },
    { name: 'New Orleans, USA',       lng: -90.07, utc: -6 },
    { name: 'Minneapolis, USA',       lng: -93.26, utc: -6 },
    { name: 'Salt Lake City, USA',    lng:-111.89, utc: -7 },
    { name: 'Honolulu, Hawaii',       lng:-157.86, utc:-10 },
    { name: 'Anchorage, Alaska',      lng:-149.90, utc: -9 },
  ]},
  { region: 'North America — Canada & Mexico', cities: [
    { name: 'Toronto, Canada',        lng: -79.38, utc: -5 },
    { name: 'Montreal, Canada',       lng: -73.57, utc: -5 },
    { name: 'Vancouver, Canada',      lng:-123.12, utc: -8 },
    { name: 'Calgary, Canada',        lng:-114.07, utc: -7 },
    { name: 'Edmonton, Canada',       lng:-113.49, utc: -7 },
    { name: 'Ottawa, Canada',         lng: -75.70, utc: -5 },
    { name: 'Winnipeg, Canada',       lng: -97.14, utc: -6 },
    { name: 'Quebec City, Canada',    lng: -71.21, utc: -5 },
    { name: 'Hamilton, Canada',       lng: -79.87, utc: -5 },
    { name: 'Halifax, Canada',        lng: -63.57, utc: -4 },
    { name: 'Mexico City, Mexico',    lng: -99.13, utc: -6 },
    { name: 'Guadalajara, Mexico',    lng:-103.35, utc: -6 },
    { name: 'Monterrey, Mexico',      lng:-100.32, utc: -6 },
    { name: 'Puebla, Mexico',         lng: -98.21, utc: -6 },
    { name: 'Tijuana, Mexico',        lng:-117.04, utc: -8 },
    { name: 'Cancún, Mexico',         lng: -86.85, utc: -5 },
  ]},
  { region: 'Central America & Caribbean', cities: [
    { name: 'Havana, Cuba',           lng: -82.38, utc: -5 },
    { name: 'Santo Domingo, Dom. Rep.',lng:-69.93, utc: -4 },
    { name: 'Port-au-Prince, Haiti',  lng: -72.34, utc: -5 },
    { name: 'Kingston, Jamaica',      lng: -76.79, utc: -5 },
    { name: 'San Juan, Puerto Rico',  lng: -66.12, utc: -4 },
    { name: 'Panama City, Panama',    lng: -79.53, utc: -5 },
    { name: 'San José, Costa Rica',   lng: -84.08, utc: -6 },
    { name: 'Guatemala City',         lng: -90.51, utc: -6 },
    { name: 'Tegucigalpa, Honduras',  lng: -87.22, utc: -6 },
    { name: 'Managua, Nicaragua',     lng: -86.25, utc: -6 },
    { name: 'San Salvador, El Salvador',lng:-89.19,utc: -6 },
    { name: 'Belmopan, Belize',       lng: -88.77, utc: -6 },
    { name: 'Nassau, Bahamas',        lng: -77.34, utc: -5 },
  ]},
  { region: 'South America', cities: [
    { name: 'São Paulo, Brazil',      lng: -46.63, utc: -3 },
    { name: 'Rio de Janeiro, Brazil', lng: -43.17, utc: -3 },
    { name: 'Brasília, Brazil',       lng: -47.93, utc: -3 },
    { name: 'Salvador, Brazil',       lng: -38.51, utc: -3 },
    { name: 'Fortaleza, Brazil',      lng: -38.54, utc: -3 },
    { name: 'Belo Horizonte, Brazil', lng: -43.94, utc: -3 },
    { name: 'Manaus, Brazil',         lng: -60.02, utc: -4 },
    { name: 'Curitiba, Brazil',       lng: -49.27, utc: -3 },
    { name: 'Recife, Brazil',         lng: -34.88, utc: -3 },
    { name: 'Porto Alegre, Brazil',   lng: -51.23, utc: -3 },
    { name: 'Belém, Brazil',          lng: -48.50, utc: -3 },
    { name: 'Goiânia, Brazil',        lng: -49.25, utc: -3 },
    { name: 'Buenos Aires, Argentina',lng: -58.38, utc: -3 },
    { name: 'Córdoba, Argentina',     lng: -64.19, utc: -3 },
    { name: 'Rosario, Argentina',     lng: -60.64, utc: -3 },
    { name: 'Mendoza, Argentina',     lng: -68.83, utc: -3 },
    { name: 'Santiago, Chile',        lng: -70.65, utc: -3 },
    { name: 'Valparaíso, Chile',      lng: -71.63, utc: -3 },
    { name: 'Concepción, Chile',      lng: -73.05, utc: -3 },
    { name: 'Lima, Peru',             lng: -77.04, utc: -5 },
    { name: 'Arequipa, Peru',         lng: -71.54, utc: -5 },
    { name: 'Cusco, Peru',            lng: -71.97, utc: -5 },
    { name: 'Bogotá, Colombia',       lng: -74.07, utc: -5 },
    { name: 'Medellín, Colombia',     lng: -75.56, utc: -5 },
    { name: 'Cali, Colombia',         lng: -76.53, utc: -5 },
    { name: 'Barranquilla, Colombia', lng: -74.78, utc: -5 },
    { name: 'Cartagena, Colombia',    lng: -75.51, utc: -5 },
    { name: 'Caracas, Venezuela',     lng: -66.90, utc: -4 },
    { name: 'Maracaibo, Venezuela',   lng: -71.64, utc: -4 },
    { name: 'Quito, Ecuador',         lng: -78.47, utc: -5 },
    { name: 'Guayaquil, Ecuador',     lng: -79.88, utc: -5 },
    { name: 'La Paz, Bolivia',        lng: -68.15, utc: -4 },
    { name: 'Santa Cruz, Bolivia',    lng: -63.17, utc: -4 },
    { name: 'Sucre, Bolivia',         lng: -65.26, utc: -4 },
    { name: 'Asunción, Paraguay',     lng: -57.64, utc: -4 },
    { name: 'Montevideo, Uruguay',    lng: -56.16, utc: -3 },
    { name: 'Georgetown, Guyana',     lng: -58.16, utc: -4 },
    { name: 'Paramaribo, Suriname',   lng: -55.17, utc: -3 },
    { name: 'Cayenne, Fr. Guiana',    lng: -52.33, utc: -3 },
  ]},
  { region: 'Africa — North Africa', cities: [
    { name: 'Cairo, Egypt',           lng:  31.24, utc:  2 },
    { name: 'Alexandria, Egypt',      lng:  29.92, utc:  2 },
    { name: 'Giza, Egypt',            lng:  31.21, utc:  2 },
    { name: 'Casablanca, Morocco',    lng:  -7.59, utc:  0 },
    { name: 'Rabat, Morocco',         lng:  -6.84, utc:  0 },
    { name: 'Marrakech, Morocco',     lng:  -7.99, utc:  0 },
    { name: 'Algiers, Algeria',       lng:   3.06, utc:  1 },
    { name: 'Oran, Algeria',          lng:  -0.63, utc:  1 },
    { name: 'Tunis, Tunisia',         lng:  10.18, utc:  1 },
    { name: 'Tripoli, Libya',         lng:  13.19, utc:  2 },
    { name: 'Benghazi, Libya',        lng:  20.07, utc:  2 },
  ]},
  { region: 'Africa — Sub-Saharan', cities: [
    { name: 'Lagos, Nigeria',         lng:   3.38, utc:  1 },
    { name: 'Kano, Nigeria',          lng:   8.52, utc:  1 },
    { name: 'Ibadan, Nigeria',        lng:   3.90, utc:  1 },
    { name: 'Abuja, Nigeria',         lng:   7.49, utc:  1 },
    { name: 'Nairobi, Kenya',         lng:  36.82, utc:  3 },
    { name: 'Mombasa, Kenya',         lng:  39.66, utc:  3 },
    { name: 'Addis Ababa, Ethiopia',  lng:  38.74, utc:  3 },
    { name: 'Dar es Salaam, Tanzania',lng:  39.27, utc:  3 },
    { name: 'Johannesburg, S. Africa',lng:  28.04, utc:  2 },
    { name: 'Cape Town, S. Africa',   lng:  18.42, utc:  2 },
    { name: 'Durban, S. Africa',      lng:  31.02, utc:  2 },
    { name: 'Pretoria, S. Africa',    lng:  28.19, utc:  2 },
    { name: 'Kinshasa, DR Congo',     lng:  15.32, utc:  1 },
    { name: 'Lubumbashi, DR Congo',   lng:  27.48, utc:  2 },
    { name: 'Luanda, Angola',         lng:  13.23, utc:  1 },
    { name: 'Maputo, Mozambique',     lng:  32.59, utc:  2 },
    { name: 'Kampala, Uganda',        lng:  32.58, utc:  3 },
    { name: 'Kigali, Rwanda',         lng:  30.06, utc:  2 },
    { name: 'Dakar, Senegal',         lng: -17.44, utc:  0 },
    { name: 'Abidjan, Ivory Coast',   lng:  -4.03, utc:  0 },
    { name: 'Accra, Ghana',           lng:  -0.19, utc:  0 },
    { name: 'Khartoum, Sudan',        lng:  32.53, utc:  2 },
    { name: 'Harare, Zimbabwe',       lng:  31.05, utc:  2 },
    { name: 'Lusaka, Zambia',         lng:  28.28, utc:  2 },
    { name: 'Antananarivo, Madagascar',lng: 47.51, utc:  3 },
    { name: 'Yaoundé, Cameroon',      lng:  11.52, utc:  1 },
    { name: 'Douala, Cameroon',       lng:   9.71, utc:  1 },
    { name: 'Bamako, Mali',           lng:  -8.00, utc:  0 },
    { name: 'Conakry, Guinea',        lng: -13.68, utc:  0 },
    { name: 'Freetown, Sierra Leone', lng: -13.23, utc:  0 },
    { name: 'Monrovia, Liberia',      lng: -10.80, utc:  0 },
    { name: 'Lomé, Togo',             lng:   1.22, utc:  0 },
    { name: 'Cotonou, Benin',         lng:   2.44, utc:  1 },
    { name: 'Niamey, Niger',          lng:   2.11, utc:  1 },
    { name: 'Ouagadougou, Burkina Faso',lng:-1.54,utc:  0 },
    { name: 'Mogadishu, Somalia',     lng:  45.34, utc:  3 },
    { name: 'Asmara, Eritrea',        lng:  38.93, utc:  3 },
    { name: 'Djibouti, Djibouti',     lng:  43.15, utc:  3 },
    { name: 'Gaborone, Botswana',     lng:  25.91, utc:  2 },
    { name: 'Windhoek, Namibia',      lng:  17.08, utc:  2 },
  ]},
  { region: 'Oceania', cities: [
    { name: 'Sydney, Australia',      lng: 151.21, utc: 10 },
    { name: 'Melbourne, Australia',   lng: 144.96, utc: 10 },
    { name: 'Brisbane, Australia',    lng: 153.03, utc: 10 },
    { name: 'Perth, Australia',       lng: 115.86, utc:  8 },
    { name: 'Adelaide, Australia',    lng: 138.60, utc:  9.5},
    { name: 'Gold Coast, Australia',  lng: 153.43, utc: 10 },
    { name: 'Canberra, Australia',    lng: 149.13, utc: 10 },
    { name: 'Newcastle, Australia',   lng: 151.78, utc: 10 },
    { name: 'Hobart, Australia',      lng: 147.33, utc: 10 },
    { name: 'Darwin, Australia',      lng: 130.84, utc:  9.5},
    { name: 'Auckland, New Zealand',  lng: 174.76, utc: 12 },
    { name: 'Wellington, New Zealand',lng: 174.78, utc: 12 },
    { name: 'Christchurch, NZ',       lng: 172.64, utc: 12 },
    { name: 'Hamilton, New Zealand',  lng: 175.28, utc: 12 },
    { name: 'Port Moresby, PNG',      lng: 147.18, utc: 10 },
    { name: 'Suva, Fiji',             lng: 178.42, utc: 12 },
    { name: 'Nouméa, New Caledonia',  lng: 166.45, utc: 11 },
    { name: 'Apia, Samoa',            lng:-171.75, utc: 13 },
    { name: 'Papeete, Fr. Polynesia', lng:-149.57, utc:-10 },
    { name: 'Nuku\'alofa, Tonga',     lng:-175.20, utc: 13 },
    { name: 'Honiara, Solomon Is.',   lng: 159.95, utc: 11 },
    { name: 'Port Vila, Vanuatu',     lng: 168.32, utc: 11 },
    { name: 'Tarawa, Kiribati',       lng: 173.00, utc: 12 },
    { name: 'Majuro, Marshall Is.',   lng: 171.38, utc: 12 },
    { name: 'Hagåtña, Guam',          lng: 144.75, utc: 10 },
  ]},
];
